# Generated by Django 4.0 on 2023-08-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_client_phone_and_more'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.TextField(verbose_name='Неисправность')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated_dt', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение')),
                ('order_status', models.TextField(choices=[('open', 'открыта'), ('closed', 'закрыта'), ('in progress', 'в работе'), ('need info', 'нужна информация')], verbose_name='Статус заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client', verbose_name='Клиент')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devices.deviceinfield', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'orders',
            },
        ),
    ]
