# Generated by Django 4.2.4 on 2023-08-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, null=True, verbose_name='Ориентировочная стоимость'),
        ),
    ]
