# Generated by Django 4.2.4 on 2023-09-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(through='services.ServiceItem', to='services.service', verbose_name='Услуга'),
        ),
    ]
