# Generated by Django 4.0 on 2023-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reklam_company',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рекламная компания'),
        ),
    ]
