# Generated by Django 4.0 on 2023-08-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
                ('brand', models.CharField(max_length=10, verbose_name='Бренд')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceInField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(unique=True, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Добавляемое устройство',
                'verbose_name_plural': 'Добавляемые устройства',
                'db_table': 'devices_in_fields',
            },
        ),
    ]
